# Generated by Django 4.2.1 on 2023-05-05 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_remove_candidate_designation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Employee',
        ),
    ]
